reformatted /home/ec2-user/ston/exp/metric/ACGPN/data/base_data_loader.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/data/base_dataset.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/data/custom_dataset_data_loader.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/data/data_loader.py
reformatted /home/ec2-user/ston/dataloader/viton_dataset.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/data/aligned_dataset.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/models/base_model.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/models/models.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/data/image_folder.py
reformatted /home/ec2-user/ston/dataloader/dresscode_dataset.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/options/test_options.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/options/base_options.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/test.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/util/image_pool.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/tps_grid_gen.py
reformatted /home/ec2-user/ston/exp/metric/DAFlow/data/data_process/draw_keypoints.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/util/util.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/models/pix2pixHD_model.py
reformatted /home/ec2-user/ston/exp/metric/DAFlow/data/data_process/get_img_agnostic.py
reformatted /home/ec2-user/ston/exp/metric/DAFlow/datasets.py
reformatted /home/ec2-user/ston/exp/metric/DAFlow/test.py
reformatted /home/ec2-user/ston/exp/metric/DAFlow/models/external_function.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/data/aligned_dataset_test.py
reformatted /home/ec2-user/ston/exp/metric/DAFlow/utils/utils.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/data/base_data_loader.py
reformatted /home/ec2-user/ston/exp/metric/DAFlow/models/sdafnet.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/data/data_loader_test.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/data/custom_dataset_data_loader_test.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/data/image_folder.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/data/base_dataset.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/data/viton_dataset.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/options/base_options.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/options/test_options.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/models/networks.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/util/__init__.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/test.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/util/image_pool.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/util/util.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/models/afwm.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/data/base_data_loader.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/data/aligned_dataset_test.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/data/custom_dataset_data_loader_test.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/data/data_loader_test.py
reformatted /home/ec2-user/ston/exp/metric/FS_VTON/util/flow_util.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/data/image_folder.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/data/base_dataset.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/data/viton_dataset.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/models/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/models/afwm.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/options/test_options.py
reformatted /home/ec2-user/ston/exp/metric/ACGPN/models/networks.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/options/base_options.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/test.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/util/image_pool.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/data/base_data_loader.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/models/networks.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/data/custom_dataset_data_loader_test.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/data/data_loader_test.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/data/aligned_dataset_test.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/data/image_folder.py
reformatted /home/ec2-user/ston/exp/metric/PF_AFN/util/util.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/data/base_dataset.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/models/base_network.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/data/viton_dataset.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/models/aad.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/models/afwm.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/models/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/models/rmgn_generator.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/options/test_options.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/models/encoder.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/util/__init__.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/util/image_pool.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/models/networks.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/test.py
reformatted /home/ec2-user/ston/exp/metric/exp_fid.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/options/base_options.py
reformatted /home/ec2-user/ston/exp/metric/RMGN_VITON/util/util.py
reformatted /home/ec2-user/ston/exp/metric/metrics/lpips/utils.py
reformatted /home/ec2-user/ston/exp/metric/metrics/lpips/lpips.py
reformatted /home/ec2-user/ston/exp/metric/metrics/lpips/pretrained_networks.py
reformatted /home/ec2-user/ston/exp/metric/metrics/pytorch_fid/fid_score.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/models/base_model.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/models/models.py
reformatted /home/ec2-user/ston/exp/metric/visualize.py
reformatted /home/ec2-user/ston/exp/metric/metrics/pytorch_fid/inception.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/models/tps_grid_gen.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/options/test_options.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/options/base_options.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/options/train_options.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/raw.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/raw.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/models/pix2pixHD_model.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/CDGNet.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/ImgTransforms.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/criterion.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/distributed.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/logger.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/attention.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/encoding.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/loss.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/miou.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/pyt_utils.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/transforms.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/writejson.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/utils.py
reformatted /home/ec2-user/ston/exp/runtime/CPVTON/raw.py
reformatted /home/ec2-user/ston/exp/runtime/CDGNet/utils/lovasz_losses.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/bpgm/model/blocks.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/bpgm/model/utils.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/bpgm/model/models.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/models/blocks.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/config.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/models/models.py
reformatted /home/ec2-user/ston/exp/runtime/CPVTON/networks.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/models/norms.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/raw.py
reformatted /home/ec2-user/ston/exp/runtime/ClothFlow/raw.py
reformatted /home/ec2-user/ston/exp/runtime/DensePose/raw.py
reformatted /home/ec2-user/ston/exp/runtime/FlowStyle/models/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/CVTON/models/generator.py
reformatted /home/ec2-user/ston/exp/runtime/ClothFlow/models/networks.py
reformatted /home/ec2-user/ston/exp/runtime/FlowStyle/options/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/ACGPN/models/networks.py
reformatted /home/ec2-user/ston/exp/runtime/FlowStyle/models/networks.py
reformatted /home/ec2-user/ston/exp/runtime/FlowStyle/options/test_options.py
reformatted /home/ec2-user/ston/exp/runtime/FlowStyle/raw.py
reformatted /home/ec2-user/ston/exp/runtime/FlowStyle/models/afwm.py
reformatted /home/ec2-user/ston/exp/runtime/PFAFN/models/afwm.py
reformatted /home/ec2-user/ston/exp/runtime/PFAFN/options/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/PFAFN/models/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/runtime/FlowStyle/options/base_options.py
reformatted /home/ec2-user/ston/exp/runtime/PFAFN/options/test_options.py
reformatted /home/ec2-user/ston/exp/runtime/PFAFN/raw.py
reformatted /home/ec2-user/ston/exp/runtime/PFAFN/options/base_options.py
reformatted /home/ec2-user/ston/exp/runtime/PFAFN/models/networks.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/models/base_network.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/models/aad.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/models/afwm.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/models/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/options/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/models/encoder.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/options/test_options.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/models/rmgn_generator.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/raw.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/options/base_options.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/aad.py
reformatted /home/ec2-user/ston/exp/runtime/SDAFN/raw.py
reformatted /home/ec2-user/ston/exp/runtime/RMGN/models/networks.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/base_network.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/encoder.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/mobile_unet_extractor.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/mobile_unet_extractor_test.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/afwm.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/mobile_unet_generator.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/afwm_pb.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/networks.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/afwm_test.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/pfafn/afwm_test.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/pfafn/mobile_unet_extractor.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/pfafn/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/pfafn/afwm.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/rmgn_generator.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/pfafn_encoder.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/options/test_options.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/options/test_base_options.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/res_unet_generator.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/raw.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGNLastHope/models/mobile_unet_extractor.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGNLastHope/models/mobile_unet_generator.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGNLastHope/options/test_base_options.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGNLastHope/options/test_options.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/activation.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGNLastHope/raw.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGNLastHope/models/afwm_test.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/attention/sagan.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/base_network.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/cpvton/unet.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/normalization.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/vgg.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/unet_mask_model.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/warp_model.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/raw.py
reformatted /home/ec2-user/ston/exp/runtime/SRMGN/models/style_swin.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/configs/ViTPose_base_coco_256x192.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/configs/ViTPose_base_simple_coco_256x192.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/configs/ViTPose_huge_coco_256x192.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/cpvton.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/configs/ViTPose_huge_simple_coco_256x192.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/configs/ViTPose_large_coco_256x192.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/inference.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/head/topdown_heatmap_base_head.py
reformatted /home/ec2-user/ston/exp/runtime/ShineOn/models/networks/cpvton/warp.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/losses/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/losses/classfication_loss.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/losses/heatmap_loss.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/head/topdown_heatmap_simple_head.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/losses/mse_loss.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/losses/mesh_loss.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/configs/ViTPose_large_simple_coco_256x192.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/model.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/optimizer.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/losses/multi_loss_factory.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/losses/regression_loss.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/dist_util.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/nms/nms.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/post_processing/__init__.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/nms/setup_linux.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/nms/nms_ori.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/models/backbone/vit.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/post_processing/one_euro_filter.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/post_processing/nms.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/post_processing/post_transforms.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/transform.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/util.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/top_down_eval.py
reformatted /home/ec2-user/ston/exp/runtime/utils.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/models/base_model.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/models/models.py
reformatted /home/ec2-user/ston/exp/runtime/main.py
reformatted /home/ec2-user/ston/exp/runtime/ViTPose/utils/post_processing/group.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/models/tps_grid_gen.py
reformatted /home/ec2-user/ston/exp/runtime/WUTON/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/options/test_options.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/options/train_options.py
reformatted /home/ec2-user/ston/exp/video_inference/FlowStyle/models/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/options/base_options.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/models/pix2pixHD_model.py
reformatted /home/ec2-user/ston/exp/video_inference/FlowStyle/options/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/FlowStyle/options/base_options.py
reformatted /home/ec2-user/ston/exp/video_inference/FlowStyle/options/test_options.py
reformatted /home/ec2-user/ston/exp/video_inference/FlowStyle/models/networks.py
reformatted /home/ec2-user/ston/exp/video_inference/OpenPoseCaffe/predict_pose.py
reformatted /home/ec2-user/ston/exp/video_inference/OpenPoseCaffe/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/FlowStyle/models/afwm.py
reformatted /home/ec2-user/ston/exp/video_inference/PFAFN/models/afwm.py
reformatted /home/ec2-user/ston/exp/video_inference/PFAFN/models/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/video_inference/FlowStyle/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/PFAFN/options/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/PFAFN/options/base_options.py
reformatted /home/ec2-user/ston/exp/video_inference/PFAFN/options/test_options.py
reformatted /home/ec2-user/ston/exp/video_inference/PFAFN/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/OpenPoseCaffe/visualize.py
reformatted /home/ec2-user/ston/exp/video_inference/PFAFN/models/networks.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/models/base_network.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/models/aad.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/models/afwm.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/models/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/models/encoder.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/options/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/models/rmgn_generator.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/options/test_options.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/options/base_options.py
reformatted /home/ec2-user/ston/exp/video_inference/RMGN/models/networks.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/modules/bn.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/extractor.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/modules/dense.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/modules/misc.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/modules/deeplab.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/modules/functions.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/backbone/mobilenetv2.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/AugmentCE2P.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/backbone/resnext.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/backbone/resnet.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/context_encoding/aspp.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/context_encoding/psp.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/networks/context_encoding/ocnet.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/utils/transforms.py
reformatted /home/ec2-user/ston/exp/video_inference/SCHP/modules/residual.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/aad.py
reformatted /home/ec2-user/ston/exp/video_inference/SDAFN/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/ACGPN/models/networks.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/base_network.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/afwm.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/encoder.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/mobile_unet_extractor.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/mobile_unet_extractor_test.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/mobile_unet_generator.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/networks.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/pfafn/afwm.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/pfafn/afwm_test.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/afwm_pb.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/pfafn/mobile_unet_extractor.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/pfafn/correlation/correlation.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/rmgn_generator.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/pfafn_encoder.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/options/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/afwm_test.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/res_unet_generator.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/options/test_base_options.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/options/test_options.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/options/test_video_options.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/options/base_options.py
reformatted /home/ec2-user/ston/exp/video_inference/flops_counter.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/raw.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/options/train_options.py
reformatted /home/ec2-user/ston/exp/video_inference/utils.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/estimator.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/models/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/SRMGN/models/style_swin.py
reformatted /home/ec2-user/ston/exp/video_inference/main.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/mini_utils.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/__init__.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/activations.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/add_nms.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/autoanchor.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/models/experimental.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/models/yolo.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/google_utils.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/general.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/metrics.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/plots.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/datasets.py
reformatted /home/ec2-user/ston/inf.py
error: cannot format /home/ec2-user/ston/inference.py: Cannot parse: 32:0: for idx, data in enumerate(tqdm(data_loader)):
reformatted /home/ec2-user/ston/losses/__init__.py
reformatted /home/ec2-user/ston/losses/tv_loss.py
reformatted /home/ec2-user/ston/losses/vgg_loss.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/models/common.py
reformatted /home/ec2-user/ston/models/base_model.py
reformatted /home/ec2-user/ston/models/common/correlation.py
reformatted /home/ec2-user/ston/models/common/transformer.py
reformatted /home/ec2-user/ston/models/extractors/res_fpn.py
reformatted /home/ec2-user/ston/models/extractors/mobile_fpn.py
reformatted /home/ec2-user/ston/models/extractors/rmgn_extractor.py
reformatted /home/ec2-user/ston/models/generators/mobile_unet.py
reformatted /home/ec2-user/ston/models/generators/res_unet.py
reformatted /home/ec2-user/ston/models/generators/rmgn_generator.py
reformatted /home/ec2-user/ston/models/generators/vit_mobile_unet.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/torch_utils.py
reformatted /home/ec2-user/ston/exp/video_inference/yolov7_pose/yolov7_utils/loss.py
reformatted /home/ec2-user/ston/models/warp_modules/afwm.py
reformatted /home/ec2-user/ston/opt/test_opt.py
reformatted /home/ec2-user/ston/opt/base_opt.py
reformatted /home/ec2-user/ston/models/warp_modules/mobile_afwm.py
reformatted /home/ec2-user/ston/opt/train_opt.py
reformatted /home/ec2-user/ston/pipelines/dmvton_pipeline.py
reformatted /home/ec2-user/ston/test.py
reformatted /home/ec2-user/ston/train_pb_warp.py
reformatted /home/ec2-user/ston/models/warp_modules/style_afwm.py
reformatted /home/ec2-user/ston/utils/general.py
reformatted /home/ec2-user/ston/utils/lr_utils.py
reformatted /home/ec2-user/ston/train_pf_e2e.py
reformatted /home/ec2-user/ston/utils/metrics/lpips/lpips.py
reformatted /home/ec2-user/ston/train_pf_warp.py
reformatted /home/ec2-user/ston/utils/metrics/lpips/pretrained_networks.py
reformatted /home/ec2-user/ston/utils/torch_utils.py
reformatted /home/ec2-user/ston/utils/metrics/pytorch_fid/fid_score.py
reformatted /home/ec2-user/ston/val.py
reformatted /home/ec2-user/ston/visualize.py
reformatted /home/ec2-user/ston/train_pb_e2e.py
reformatted /home/ec2-user/ston/utils/metrics/pytorch_fid/inception.py

Oh no! 💥 💔 💥
355 files reformatted, 20 files left unchanged, 1 file failed to reformat.
